# This file is a template, and might need editing before it works on your project.
image: golang:latest

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is mydomainperso.com, and that your repository is repos/projectname, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/mydomainperso.com/repos/projectname
# Thus, making a symbolic link corrects this.
before_script:
    - ln -s /builds /go/src/gitlab.com
    - cd /go/src/gitlab.com/Shadow53

stages:
    #- test
    - build

#format:
#    stage: test
#    script:
        # Add here all the dependencies, or use glide/govendor to get
        # them automatically.
        # - curl https://glide.sh/get | sh
#        - go get github.com/alecthomas/kingpin
#        - go tool vet -composites=false -shadow=true *.go
#        - go test -race $(go list ./... | grep -v /vendor/)

compile:
    stage: build
    script:
        # Add here all the dependencies, or use glide/govendor/...
        # to get them automatically.
        # Doing so manually until I learn an automatic tool
        - go get github.com/spf13/viper
        # Better put this in a Makefile
        - CGO_ENABLED=0 GOOS=android GOARCH=arm go build -buildmode exe -compiler gc -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main

        - CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -buildmode exe -compiler gc -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main
        - CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -buildmode exe -compiler gc -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main
        - CGO_ENABLED=0 GO386=sse2 GOOS=linux GOARCH=386 go build -buildmode exe -compiler gc -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main
        - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildmode exe -compiler gc -race -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main

        - CGO_ENABLED=0 GO386=sse2 GOOS=darwin GOARCH=386 go build -buildmode exe -compiler gc -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main
        - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -buildmode exe -compiler gc -race -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main

        - CGO_ENABLED=0 GO386=sse2 GOOS=windows GOARCH=386 go build -buildmode exe -compiler gc -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main
        - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -buildmode exe -compiler gc -race -o zip-builder.${GOOS}.${GOARCH} gitlab.com/Shadow53/zip-builder/main
        - tar czf binaries.tar.gz bin/
    artifacts:
        paths:
            - binaries.tar.gz
