[[apps]]
  name = "microgms"
  package_name = "com.google.android.gms"
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  # Needs to be in priv-app to be doze/data-saver whitelisted
  destination = "/system/priv-app/GmsCore/GmsCore.apk"
  remove_files = [
    "/system/app/GmsCore",
    "/system/priv-app/GmsCore",
    "/system/priv-app/GmsCore_update",
    "/system/app/PrebuiltGmsCore",
    "/system/priv-app/PrebuiltGmsCore",
    "/system/priv-app/GmsCoreSetupPrebuilt",
    "/system/priv-app/GoogleLoginService",
    "/system/app/UnifiedNlp",
    "/system/priv-app/com.qualcomm.location"
  ]
  install_remove_files = [
    #"/data/data/com.google.android.gms"
  ]
  doze_whitelist = true
  data_saver_whitelist = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "microgsf"
  package_name = "com.google.android.gsf"
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/GsfProxy/GsfProxy.apk"
  remove_files = [
    "/system/app/GsfProxy",
    "/system/priv-app/GsfProxy",
    "/system/priv-app/GoogleServicesFramework"
  ]
  install_remove_files = [
    #"/data/data/com.google.android.gsf"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "playstore-patched"
  package_name = "com.android.vending"
  url = "https://nanolx.org/apk/Phonesky.apk"
  sha256 = "e52d5ddfef2995208151bb6120768231ae900a6a996b348021f7fa06b91234d9"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky",
    "/system/priv-app/YalpStore"
  ]
  install_remove_files = [
    "/data/data/com.android.vending"
  ]
  permissions = ["FAKE_PACKAGE_SIGNATURE"]
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "playstore"
  package_name = "com.android.vending"
  url = "https://raw.githubusercontent.com/opengapps/arm/master/priv-app/com.android.vending/14/240-320-480/80912400.apk"
  sha256 = "8272425ead720bd1b9aa6aac91494e36b9d57a797e046a0ceb31a6f704371fcd"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky",
    "/system/priv-app/YalpStore"
  ]
  install_remove_files = [
    "/data/data/com.android.vending"
  ]
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "fakestore"
  package_name = "com.android.vending"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky"
  ]
  install_remove_files = [
    "/data/data/com.android.vending"
  ]
  permissions = ["FAKE_PACKAGE_SIGNATURE"]
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "unifiednlp"
  package_name = "com.google.android.gms"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/UnifiedNlp/UnifiedNlp.apk"
  remove_files = [
    "/system/priv-app/com.qualcomm.location"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "mozillanlp"
  package_name = "org.microg.nlp.backend.ichnaea"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/MozillaNlpBackend/MozillaNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "dejavu"
  package_name = "org.fitchfamily.android.dejavu"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/DejaVuNlpBackend/DejaVuNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "nominatim"
  package_name = "org.microg.nlp.backend.nominatim"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/NominatimNlpBackend/NominatimNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[zips]]
  name = "microg-playstore"
  apps = [
    "microgms",
    "microgsf",
    "playstore",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]

[[zips]]
  name = "microg-playstore-patched"
  apps = [
    "microgms",
    "microgsf",
    "playstore-patched",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]

[[zips]]
  name = "microg"
  apps = [
    "microgms",
    "microgsf",
    "fakestore",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]

[[zips]]
  name = "playstore-patched"
  apps = [
    "playstore-patched"
  ]

[[zips]]
  name = "playstore"
  apps = [
    "playstore"
  ]

[[zips]]
  name = "unifiednlp"
  apps = [
    "unifiednlp",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]
