[[apps]]
  name = "microgms"
  package_name = "com.google.android.gms"
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  # Needs to be in priv-app to be doze/data-saver whitelisted
  destination = "/system/priv-app/GmsCore/GmsCore.apk"
  install_remove_files = [
    "/system/app/GmsCore",
    "/system/priv-app/GmsCore",
    "/system/priv-app/GmsCore_update",
    "/system/app/PrebuiltGmsCore",
    "/system/priv-app/PrebuiltGmsCore",
    "/system/priv-app/GmsCoreSetupPrebuilt",
    "/system/priv-app/GoogleLoginService",
    "/system/app/UnifiedNlp"
  ]
  remove_files = [
    "/system/priv-app/com.qualcomm.location"
  ]
  doze_whitelist = true
  data_saver_whitelist = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "microgsf"
  package_name = "com.google.android.gsf"
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/GsfProxy/GsfProxy.apk"
  install_remove_files = [
    "/system/app/GsfProxy",
    "/system/priv-app/GsfProxy",
    "/system/priv-app/GoogleServicesFramework"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "playstore-patched"
  package_name = "com.android.vending"
  url = "https://gitlab.com/Nanolx/NanoMod/raw/master/Full/system/priv-app/Phonesky/Phonesky.apk"
  sha256 = "ce3f5610bd536dbbd59f9eab58b84dab9325f7949a45e7a9d410b6236c5e1e61"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  install_remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky"
  ]
  permissions = ["FAKE_PACKAGE_SIGNATURE"]
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "playstore"
  package_name = "com.android.vending"
  url = "https://raw.githubusercontent.com/opengapps/all/master/priv-app/com.android.vending/14/240-320-480/80837400.apk"
  sha256 = "1216ccaa49fff2591c8283dec62b49326f1242d879d979763060ee414515f1f7"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  install_remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky"
  ]
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "fakestore"
  package_name = "com.android.vending"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  install_remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky"
  ]
  permissions = ["FAKE_PACKAGE_SIGNATURE"]
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "unifiednlp"
  package_name = "com.google.android.gms"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/UnifiedNlp/UnifiedNlp.apk"
  remove_files = [
    "/system/priv-app/com.qualcomm.location"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "mozillanlp"
  package_name = "org.microg.nlp.backend.ichnaea"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/MozillaNlpBackend/MozillaNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "nominatim"
  package_name = "org.microg.nlp.backend.nominatim"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/NominatimNlpBackend/NominatimNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[zips]]
  name = "microg-playstore"
  apps = [
    "microgms",
    "microgsf",
    "playstore-patched",
    "mozillanlp",
    "nominatim"
  ]

[[zips]]
  name = "microg"
  apps = [
    "microgms",
    "microgsf",
    "fakestore",
    "mozillanlp",
    "nominatim"
  ]

[[zips]]
  name = "playstore-patched"
  apps = [
    "playstore-patched"
  ]

[[zips]]
  name = "playstore"
  apps = [
    "playstore"
  ]

[[zips]]
  name = "unifiednlp"
  apps = [
    "unifiednlp",
    "mozillanlp",
    "nominatim"
  ]
