[[apps]]
  name = "microgms"
  package_name = "com.google.android.gms"
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  # Needs to be in priv-app to be doze/data-saver whitelisted
  destination = "/system/priv-app/GmsCore/GmsCore.apk"
  remove_files = [
    "/system/app/GmsCore",
    "/system/priv-app/GmsCore",
    "/system/priv-app/GmsCore_update",
    "/system/app/PrebuiltGmsCore",
    "/system/priv-app/PrebuiltGmsCore",
    "/system/priv-app/GmsCoreSetupPrebuilt",
    "/system/priv-app/GoogleLoginService",
    "/system/app/UnifiedNlp",
    "/system/priv-app/com.qualcomm.location"
  ]
  install_remove_files = [
    #"/data/data/com.google.android.gms"
  ]
  doze_whitelist = true
  data_saver_whitelist = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "microgsf"
  package_name = "com.google.android.gsf"
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/GsfProxy/GsfProxy.apk"
  remove_files = [
    "/system/app/GsfProxy",
    "/system/priv-app/GsfProxy",
    "/system/priv-app/GoogleServicesFramework"
  ]
  install_remove_files = [
    #"/data/data/com.google.android.gsf"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "playstore-patched"
  package_name = "com.android.vending"
  url = "https://gitlab.com/Nanolx/NanoMod/raw/master/Full/system/priv-app/Phonesky/Phonesky.apk"
  sha256 = "ce3f5610bd536dbbd59f9eab58b84dab9325f7949a45e7a9d410b6236c5e1e61"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky",
    "/system/priv-app/YalpStore"
  ]
  install_remove_files = [
    "/data/data/com.android.vending"
  ]
  permissions = ["FAKE_PACKAGE_SIGNATURE"]
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "playstore"
  package_name = "com.android.vending"
  url = "https://raw.githubusercontent.com/opengapps/all/master/priv-app/com.android.vending/14/240-320-480/80844000.apk"
  sha256 = "8939d4a8477f450689cc16e9af3e9625a7b1e11125d7bbe2ecc9b53aa727f182"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky",
    "/system/priv-app/YalpStore"
  ]
  install_remove_files = [
    "/data/data/com.android.vending"
  ]
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"
    [[apps.androidversion.arch]]
    arch = "arm"
    url = "https://raw.githubusercontent.com/opengapps/arm/master/priv-app/com.android.vending/14/240-320-480/80853900.apk"
    sha256 = "6e6113c51238862bc8602fff52e5a3b29b54e7cb775b53445d5e61acf115f4b0"
    [[apps.androidversion.arch]]
    arch = "arm64"
    url = "https://raw.githubusercontent.com/opengapps/arm/master/priv-app/com.android.vending/14/240-320-480/80853900.apk"
    sha256 = "6e6113c51238862bc8602fff52e5a3b29b54e7cb775b53445d5e61acf115f4b0"
    [[apps.androidversion.arch]]
    arch = "x86"
    url = "https://raw.githubusercontent.com/opengapps/x86/master/priv-app/com.android.vending/14/240-320-480/80853900.apk"
    sha256 = "6e6113c51238862bc8602fff52e5a3b29b54e7cb775b53445d5e61acf115f4b0"
    [[apps.androidversion.arch]]
    arch = "x86_64"
    url = "https://raw.githubusercontent.com/opengapps/x86_64/master/priv-app/com.android.vending/14/240-320-480/80853900.apk"
    sha256 = "6e6113c51238862bc8602fff52e5a3b29b54e7cb775b53445d5e61acf115f4b0"

[[apps]]
  name = "fakestore"
  package_name = "com.android.vending"
  destination = "/system/priv-app/Phonesky/Phonesky.apk"
  remove_files = [
    "/system/priv-app/PlayStore",
    "/system/priv-app/FakeStore",
    "/system/priv-app/Phonesky"
  ]
  install_remove_files = [
    "/data/data/com.android.vending"
  ]
  permissions = ["FAKE_PACKAGE_SIGNATURE"]
  url = "https://microg.org/fdroid/repo"
  is_fdroid_repo = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "unifiednlp"
  package_name = "com.google.android.gms"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/UnifiedNlp/UnifiedNlp.apk"
  remove_files = [
    "/system/priv-app/com.qualcomm.location"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "mozillanlp"
  package_name = "org.microg.nlp.backend.ichnaea"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/MozillaNlpBackend/MozillaNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "dejavu"
  package_name = "org.fitchfamily.android.dejavu"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/DejaVuNlpBackend/DejaVuNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "nominatim"
  package_name = "org.microg.nlp.backend.nominatim"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/NominatimNlpBackend/NominatimNlpBackend.apk"
  [[apps.androidversion]]
    number = "5.0"

[[zips]]
  name = "microg-playstore"
  apps = [
    "microgms",
    "microgsf",
    "playstore",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]

[[zips]]
  name = "microg-playstore-patched"
  apps = [
    "microgms",
    "microgsf",
    "playstore-patched",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]

[[zips]]
  name = "microg"
  apps = [
    "microgms",
    "microgsf",
    "fakestore",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]

[[zips]]
  name = "playstore-patched"
  apps = [
    "playstore-patched"
  ]

[[zips]]
  name = "playstore"
  apps = [
    "playstore"
  ]

[[zips]]
  name = "unifiednlp"
  apps = [
    "unifiednlp",
    "mozillanlp",
    "dejavu",
    "nominatim"
  ]
