[[files]]
  name = "emojione"
  url = "https://github.com/emojione/emojione-assets/releases/download/4.5/emojione-android.ttf"
  sha256sum = "5a8ec97548326235f427dff60749bdbd525de20383c42b1ae73f3bae883f58c2"
  destination = "/system/fonts/NotoColorEmoji.ttf"
  [[files.androidversion]]
    number = "5.0"

[[zips]]
  name = "emojione"
  files = ["emojione"]
