[[files]]
  name = "emojione"
  url = "https://raw.githubusercontent.com/emojione/emojione/master/extras/fonts/emojione-android.ttf"
  md5 = "6cb875b80d51f9a26eb05db7f9779011"
  destination = "/system/fonts/NotoColorEmoji.ttf"
  [[files.androidversion]]
    number = "5.0"

[[zips]]
  name = "emojione"
  files = ["emojione"]
