[[files]]
  name = "emojione"
  url = "https://github.com/emojione/emojione-assets/releases/download/3.1.2/emojione-android.ttf"
  md5 = "2e8e64f2e134a15357f0b8dd3a77c42a"
  destination = "/system/fonts/NotoColorEmoji.ttf"
  [[files.androidversion]]
    number = "5.0"

[[zips]]
  name = "emojione"
  files = ["emojione"]
