[[apps]]
  name = "f-droid"
  package_name = "org.fdroid.fdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/FDroid/FDroid.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "f-droid-priv"
  package_name = "org.fdroid.fdroid.privileged"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/FDroidPrivilegedExt/FDroidPrivilegedExt.apk"
  grant_system_user = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "davdroid"
  package_name = "at.bitfire.davdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/DAVDroid/DAVDroid.apk"
  doze_whitelist = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "openlauncher"
  package_name = "com.benny.openlauncher"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenLauncher/OpenLauncher.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opentasks"
  package_name = "org.dmfs.tasks"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenTasks/OpenTasks.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "etar"
  package_name = "ws.xsoh.etar"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Etar/Etar.apk"
  remove_files = ["/system/app/Calendar"]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "anysoftkb"
  package_name = "com.menny.android.anysoftkeyboard"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/AnySoftKeyboard/AnySoftKeyboard.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "firefox"
  package_name = "org.mozilla.firefox"
  url = "https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi"
  destination = "/system/app/Firefox/Firefox.apk"
  md5 = "a63e98c49d2f8795d174032dfb8980f5"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "yalpstore"
  package_name = "com.github.yeriomin.yalpstore"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/YalpStore/YalpStore.apk"
  grant_system_user = true
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "silence"
  package_name = "org.smssecure.smssecure"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Silence/Silence.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-music"
  package_name = "ch.blinkenlights.android.vanilla"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Vanilla/Vanilla.apk"
  remove_files = [
    "/system/priv-app/Eleven",
    "/system/app/Phonograph"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-cover-fetch"
  package_name = "com.kanedias.vanilla.coverfetch"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaCoverFetch/VanillaCoverFetch.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-tag-editor"
  package_name = "com.kanedias.vanilla.audiotag"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaTagEditor/VanillaTagEditor.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-lyrics"
  package_name = "com.kanedias.vanilla.lyrics"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaLyrics/VanillaLyrics.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "clock+"
  package_name = "com.philliphsu.clock2"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Clock+/Clock+.apk"
  remove_files = [
    "/system/app/DeskClock",
    "/system/app/OmniClockOSS"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opencamera"
  package_name = "net.sourceforge.opencamera"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenCamera/OpenCamera.apk"
  remove_files = [
    "/system/app/Camera2",
    "/system/app/SnapdragonCamera"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "silence"
  package_name = "org.smssecure.smssecure"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Silence/Silence.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-music"
  package_name = "ch.blinkenlights.android.vanilla"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Vanilla/Vanilla.apk"
  remove_files = [
    "/system/priv-app/Eleven",
    "/system/app/Phonograph"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-cover-fetch"
  package_name = "com.kanedias.vanilla.coverfetch"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaCoverFetch/VanillaCoverFetch.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-tag-editor"
  package_name = "com.kanedias.vanilla.audiotag"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaTagEditor/VanillaTagEditor.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-lyrics"
  package_name = "com.kanedias.vanilla.lyrics"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaLyrics/VanillaLyrics.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "clock+"
  package_name = "com.philliphsu.clock2"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Clock+/Clock+.apk"
  remove_files = [
    "/system/app/DeskClock",
    "/system/app/OmniClockOSS"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opencamera"
  package_name = "net.sourceforge.opencamera"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenCamera/OpenCamera.apk"
  remove_files = [
    "/system/app/Camera2",
    "/system/app/SnapdragonCamera"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[zips]]
  name = "fdroid"
  apps = [
    "f-droid",
    "f-droid-priv"
  ]

[[zips]]
  name = "no-gapps"
  apps = [
    "anysoftkb",
    "clock+",
    "davdroid",
    "etar",
    "f-droid",
    "f-droid-priv",
    "firefox",
    "opencamera",
    "openlauncher",
    "opentasks",
    "silence",
    "vanilla-music",
    "vanilla-cover-fetch",
    "vanilla-lyrics",
    "vanilla-tag-editor",
    "yalpstore"
  ]
