[[apps]]
  name = "amazefm"
  package_name = "com.amaze.filemanager"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Amaze/Amaze.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "anysoftkb"
  package_name = "com.menny.android.anysoftkeyboard"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/AnySoftKeyboard/AnySoftKeyboard.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "calculator"
  package_name = "com.xlythe.calculator.material"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Calculator/Calculator.apk"
  remove_files = [
    "/system/app/ExactCalculator"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "camera-roll"
  package_name = "us.koller.cameraroll"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/CameraRoll/CameraRoll.apk"
  remove_files = [
    "/system/app/Gallery2",
    "/system/priv-app/Gallery2"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "clock+"
  package_name = "com.philliphsu.clock2"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Clock+/Clock+.apk"
  remove_files = [
    "/system/app/DeskClock",
    "/system/app/OmniClockOSS"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "davdroid"
  package_name = "at.bitfire.davdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/DAVDroid/DAVDroid.apk"
  doze_whitelist = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "duckduckgo"
  package_name = "com.duckduckgo.mobile.android"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/DuckDuckGo/DuckDuckGo.apk"
  remove_files = [
    "/system/app/QuickSearchBox"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "etar"
  package_name = "ws.xsoh.etar"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Etar/Etar.apk"
  remove_files = ["/system/app/Calendar"]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "f-droid"
  package_name = "org.fdroid.fdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/FDroid/FDroid.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "f-droid-priv"
  package_name = "org.fdroid.fdroid.privileged"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/FDroidPrivilegedExtension/FDroidPrivilegedExtension.apk"
  grant_system_user = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "fennec"
  package_name = "org.mozilla.fennec_fdroid"
  destination = "/system/app/Fennec/Fennec.apk"
  url = "https://f-droid.org/repo/org.mozilla.fennec_fdroid_580200.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "firefox"
  package_name = "org.mozilla.firefox"
  url = "https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi"
  destination = "/system/app/Firefox/Firefox.apk"
  md5 = "aea1be9292a3a8ba33a1289ffa3e68b9"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "galaxy"
  package_name = "in.dragons.galaxy"
  url = "https://github.com/whyorean/Galaxy/releases/download/v1.0.4/Galaxy_Release_1.0.4.apk"
  destination = "/system/priv-app/GalaxyStore/GalaxyStore.apk"
  grant_system_user = true
  doze_whitelist_except_idle = true
  permissions = ["READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE", "REQUEST_INSTALL_PACKAGES", "INSTALL_PACKAGES"]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "hayai-launcher"
  package_name = "com.hayaisoftware.launcher"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/HayaiLauncher/HayaiLauncher.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet",
    "/system/priv-app/crDroidHome"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "icsdroid"
  package_name = "at.bitfire.icsdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/ICSDroid/ICSDroid.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "k9mail"
  package_name = "com.fsck.k9"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/K9Mail/K9Mail.apk"
  remove_files = [
    "/system/app/Email"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "lawnchair"
  package_name = "ch.deletescape.lawnchair.plah"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Lawnchair/Lawnchair.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet",
    "/system/priv-app/crDroidHome"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "lawnfeed"
  package_name = "ch.deletescape.lawnchair.lawnfeed"
  url = "https://storage.codebucket.de/lawnchair/1.1.0.1742/Lawnfeed-1.1.0.1742.apk"
  destination = "/system/app/Lawnfeed/Lawnfeed.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "lightning"
  package_name = "acr.browser.lightning"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Lightning/Lightning.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "maps"
  package_name = "com.github.axet.maps"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/MAPS/MAPS.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "omni-notes"
  package_name = "it.feio.android.omninotes.foss"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OmniNotes/OmniNotes.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opencamera"
  package_name = "net.sourceforge.opencamera"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenCamera/OpenCamera.apk"
  remove_files = [
    "/system/app/Camera2",
    "/system/app/SnapdragonCamera",
    "/system/app/SnapdragonCamera2",
    "/system/priv-app/Snap"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "openlauncher"
  package_name = "com.benny.openlauncher"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenLauncher/OpenLauncher.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet",
    "/system/priv-app/crDroidHome"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opentasks"
  package_name = "org.dmfs.tasks"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenTasks/OpenTasks.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "osmand"
  package_name = "net.osmand.plus"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OSMAnd/OSMAnd.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "secuso-notes"
  package_name = "org.secuso.privacyfriendlynotes"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/PrivacyFriendlyNotes/PrivacyFriendlyNotes.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "silence"
  package_name = "org.smssecure.smssecure"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Silence/Silence.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "simple-gallery"
  package_name = "com.simplemobiletools.gallery"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/SimpleGallery/SimpleGallery.apk"
  remove_files = [
    "/system/app/Gallery2",
    "/system/priv-app/Gallery2"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-cover-fetch"
  package_name = "com.kanedias.vanilla.coverfetch"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaCoverFetch/VanillaCoverFetch.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-lyrics"
  package_name = "com.kanedias.vanilla.lyrics"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaLyrics/VanillaLyrics.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-music"
  package_name = "ch.blinkenlights.android.vanilla"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Vanilla/Vanilla.apk"
  remove_files = [
    "/system/priv-app/Eleven",
    "/system/app/Phonograph"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vanilla-tag-editor"
  package_name = "com.kanedias.vanilla.audiotag"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VanillaTagEditor/VanillaTagEditor.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vinyl-music"
  package_name = "com.poupa.vinylmusicplayer"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VinylMusic/VinylMusic.apk"
  remove_files = [
    "/system/priv-app/Eleven",
    "/system/app/Phonograph",
    "/system/app/crDroidMusic"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "yalpstore"
  package_name = "com.github.yeriomin.yalpstore"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/YalpStore/YalpStore.apk"
  grant_system_user = true
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[zips]]
  name = "fdroid"
  apps = [
    "f-droid",
    "f-droid-priv"
  ]

[[zips]]
  name = "no-gapps-pico"
  apps = [
    "f-droid",
    "f-droid-priv",
    "yalpstore"
  ]

[[zips]]
  name = "no-gapps-nano"
  apps = [
    "davdroid",
    "duckduckgo",
    "f-droid",
    "f-droid-priv",
    "icsdroid",
    "yalpstore"
  ]

[[zips]]
  name = "no-gapps-micro"
  apps = [
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    "openlauncher",
    "yalpstore"
  ]

[[zips]]
  name = "no-gapps-mini"
  apps = [
    "amazefm",
    "calculator",
    "camera-roll",
    "clock+",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    "maps",
    "openlauncher",
    "osmand",
    "silence",
    "yalpstore"
  ]

[[zips]]
  # Unlike OpenGapps Full, these apps replace stock options
  name = "no-gapps-full"
  apps = [
    "amazefm",
    "calculator",
    "camera-roll",
    "clock+",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    #"fennec",
    #"firefox",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    "lightning",
    "maps",
    "omni-notes",
    "openlauncher",
    "osmand",
    "silence",
    #"vanilla-music",
    #"vanilla-cover-fetch",
    #"vanilla-lyrics",
    #"vanilla-tag-editor",
    "vinyl-music",
    "yalpstore"
  ]

[[zips]]
  name = "no-gapps-stock"
  apps = [
    "amazefm",
    "anysoftkb",
    "calculator",
    "camera-roll",
    "clock+",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    #"fennec",
    #"firefox",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    "lightning",
    "maps",
    "omni-notes",
    "opencamera",
    "openlauncher",
    "opentasks",
    #"osmand",
    "silence",
    #"vanilla-music",
    #"vanilla-cover-fetch",
    #"vanilla-lyrics",
    #"vanilla-tag-editor",
    "vinyl-music",
    "yalpstore"
  ]

[[zips]]
  name = "no-gapps-custom"
  apps = [
    "amazefm",
    "anysoftkb",
    #"calculator",
    "camera-roll",
    #"clock+",
    "davdroid",
    "duckduckgo",
    #"etar",
    "f-droid",
    "f-droid-priv",
    "fennec",
    #"firefox",
    "galaxy",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    #"lawnchair",
    #"lawnfeed",
    #"lightning",
    "maps",
    "omni-notes",
    "opencamera",
    "openlauncher",
    #"opentasks",
    #"osmand",
    #"silence",
    #"simple-gallery",
    #"vanilla-music",
    #"vanilla-cover-fetch",
    #"vanilla-lyrics",
    #"vanilla-tag-editor",
    "vinyl-music",
    #"yalpstore"
  ]
