[[apps]]
  name = "amazefm"
  package_name = "com.amaze.filemanager"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Amaze/Amaze.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "anysoftkb"
  package_name = "com.menny.android.anysoftkeyboard"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/AnySoftKeyboard/AnySoftKeyboard.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "calculator"
  package_name = "com.xlythe.calculator.material"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Calculator/Calculator.apk"
  remove_files = [
    "/system/app/ExactCalculator"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "camera-roll"
  package_name = "us.koller.cameraroll"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/CameraRoll/CameraRoll.apk"
  remove_files = [
    "/system/app/Gallery2",
    "/system/priv-app/Gallery2"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "clock+"
  package_name = "com.philliphsu.clock2"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Clock+/Clock+.apk"
  remove_files = [
    "/system/app/DeskClock",
    "/system/app/OmniClockOSS"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "davdroid"
  package_name = "at.bitfire.davdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/DAVDroid/DAVDroid.apk"
  doze_whitelist = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "duckduckgo"
  package_name = "com.duckduckgo.mobile.android"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/DuckDuckGo/DuckDuckGo.apk"
  remove_files = [
    "/system/app/QuickSearchBox"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "etar"
  package_name = "ws.xsoh.etar"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Etar/Etar.apk"
  remove_files = ["/system/app/Calendar"]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "f-droid"
  package_name = "org.fdroid.fdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/FDroid/FDroid.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "f-droid-priv"
  package_name = "org.fdroid.fdroid.privileged"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/FDroidPrivilegedExtension/FDroidPrivilegedExtension.apk"
  grant_system_user = true
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "fennec"
  package_name = "org.mozilla.fennec_fdroid"
  destination = "/system/app/Fennec/Fennec.apk"
  url = "https://f-droid.org/repo/org.mozilla.fennec_fdroid_610200.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "aurora"
  package_name = "com.dragons.aurora"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/AuroraStore/AuroraStore.apk"
  grant_system_user = true
  doze_whitelist_except_idle = true
  permissions = ["READ_EXTERNAL_STORAGE", "WRITE_EXTERNAL_STORAGE", "REQUEST_INSTALL_PACKAGES", "INSTALL_PACKAGES"]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "hayai-launcher"
  package_name = "com.hayaisoftware.launcher"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/HayaiLauncher/HayaiLauncher.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet",
    "/system/priv-app/crDroidHome"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "icsdroid"
  package_name = "at.bitfire.icsdroid"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/ICSDroid/ICSDroid.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "k9mail"
  package_name = "com.fsck.k9"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/K9Mail/K9Mail.apk"
  remove_files = [
    "/system/app/Email"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "lawnchair"
  package_name = "ch.deletescape.lawnchair.plah"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/Lawnchair/Lawnchair.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet",
    "/system/priv-app/crDroidHome"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "maps"
  package_name = "com.github.axet.maps"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/MAPS/MAPS.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "omni-notes"
  package_name = "it.feio.android.omninotes.foss"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OmniNotes/OmniNotes.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opencamera"
  package_name = "net.sourceforge.opencamera"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenCamera/OpenCamera.apk"
  remove_files = [
    "/system/app/Camera2",
    "/system/app/SnapdragonCamera",
    "/system/app/SnapdragonCamera2",
    "/system/priv-app/Snap"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "openlauncher"
  package_name = "com.benny.openlauncher"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenLauncher/OpenLauncher.apk"
  remove_files = [
    "/system/priv-app/Launcher3",
    "/system/priv-app/Trebuchet",
    "/system/priv-app/crDroidHome"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "opentasks"
  package_name = "org.dmfs.tasks"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OpenTasks/OpenTasks.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "osmand"
  package_name = "net.osmand.plus"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/OSMAnd/OSMAnd.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "qksms"
  package_name = "com.moez.QKSMS"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/QKSMS/QKSMS.apk"
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "vinyl-music"
  package_name = "com.poupa.vinylmusicplayer"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/app/VinylMusic/VinylMusic.apk"
  remove_files = [
    "/system/priv-app/Eleven",
    "/system/app/Phonograph",
    "/system/app/crDroidMusic"
  ]
  [[apps.androidversion]]
    number = "5.0"

[[apps]]
  name = "yalpstore"
  package_name = "com.github.yeriomin.yalpstore"
  url = "https://f-droid.org/repo"
  is_fdroid_repo = true
  destination = "/system/priv-app/YalpStore/YalpStore.apk"
  grant_system_user = true
  doze_whitelist_except_idle = true
  [[apps.androidversion]]
    number = "5.0"

[[zips]]
  name = "fdroid"
  apps = [
    "f-droid",
    "f-droid-priv"
  ]

[[zips]]
  name = "aurora"
  apps = [
    "aurora"
  ]

[[zips]]
  name = "no-gapps-pico"
  apps = [
    "aurora",
    "f-droid",
    "f-droid-priv",
    #"yalpstore"
  ]

[[zips]]
  name = "no-gapps-nano"
  apps = [
    "aurora",
    "davdroid",
    "duckduckgo",
    "f-droid",
    "f-droid-priv",
    "icsdroid",
    #"yalpstore"
  ]

[[zips]]
  name = "no-gapps-micro"
  apps = [
    "aurora",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    "openlauncher",
    #"yalpstore"
  ]

[[zips]]
  name = "no-gapps-mini"
  apps = [
    "amazefm",
    "aurora",
    "calculator",
    "camera-roll",
    "clock+",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    #"maps",
    "openlauncher",
    "osmand",
    "qksms",
    #"yalpstore"
  ]

[[zips]]
  # Unlike OpenGapps Full, these apps replace stock options
  name = "no-gapps-full"
  apps = [
    "amazefm",
    "aurora",
    "calculator",
    "camera-roll",
    "clock+",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    "fennec",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    #"maps",
    "omni-notes",
    "openlauncher",
    "osmand",
    "qksms",
    "vinyl-music",
    #"yalpstore"
  ]

[[zips]]
  name = "no-gapps-stock"
  apps = [
    "amazefm",
    "anysoftkb",
    "aurora",
    "calculator",
    "camera-roll",
    "clock+",
    "davdroid",
    "duckduckgo",
    "etar",
    "f-droid",
    "f-droid-priv",
    "fennec",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    #"maps",
    "omni-notes",
    "opencamera",
    "openlauncher",
    "opentasks",
    "osmand",
    "qksms",
    "vinyl-music",
    #"yalpstore"
  ]

[[zips]]
  name = "no-gapps-custom"
  apps = [
    "amazefm",
    "anysoftkb",
    "aurora",
    #"calculator",
    #"camera-roll",
    #"clock+",
    "davdroid",
    "duckduckgo",
    #"etar",
    "f-droid",
    "f-droid-priv",
    "fennec",
    #"hayai-launcher",
    "icsdroid",
    "k9mail",
    #"lawnchair",
    "maps",
    #"omni-notes",
    "opencamera",
    #"openlauncher",
    #"opentasks",
    #"osmand",
    "qksms",
    "vinyl-music",
    #"yalpstore"
  ]
